### ISSUE TITLE
link deploy app error / "Application Error"

### ISSUE THREAD

**Issue by teddy-tama** [Zhirrr/Bioskop-Api#1]
link deploy app nya error mas, bisa minta tolong untuk dicek dan diaktifkan kembali kah??
![Screenshot 2021-04-30 141036](https://user-images.githubusercontent.com/74857809/116661153-37cd1680-a9be-11eb-9fa9-a4ddbd319d80.png)

**Comment by Zhirrr** [comment]
> link deploy app nya error mas, bisa minta tolong untuk dicek dan diaktifkan kembali kah??
> ![Screenshot 2021-04-30 141036](https://user-images.githubusercontent.com/74857809/116661153-37cd1680-a9be-11eb-9fa9-a4ddbd319d80.png)

udah bener mas, silahkan di cek hehe
